### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by beingfluid** [Ahmed-Soli/linkedin-course-downloader#28]
py downloader.py
Traceback (most recent call last):
  File "C:\Users\visha\myFiles\linkedin-course-downloader\linkedin-course-downloader\downloader.py", line 3, in <module>
    from fetch_info import fetch_courses
  File "C:\Users\visha\myFiles\linkedin-course-downloader\linkedin-course-downloader\fetch_info.py", line 5, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by Ahmed-Soli** [comment]
`from fetch_info import fetch_courses` make sure to have all the scripts in one folder
`No module named 'tqdm'` use this command in the cmd to install it `pip install tqdm`
